version: '3'
services:
  carrito-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: carrito-app
    ports:
      - "3000:3000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/carritoCompra
    depends_on:
      - mongo
    volumes:
      - ./carrito-compra:/usr/src/app
    networks:
      - carrito-network
    restart: always

  mongo:
    image: mongo:6.0
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - carrito-network

  adminer:
    image: adminer
    container_name: adminer
    ports:
      - "8080:8080"
    environment:
      - ADMINER_DEFAULT_SERVER=mongo
    depends_on:
      - mongo
    networks:
      - carrito-network
    restart: always

volumes:
  mongo-data:

networks:
  carrito-network:
